# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 2000

[bun]
symbol = '🍞 '

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[git_branch]
symbol = '🌳 '

